### ISSUE TITLE
Television Accessory showing incorrect icon

### ISSUE THREAD

**Issue by johndbritton** [karlentwistle/ruby_home#107]
@karlentwistle Thanks for releasing the new version of the gem with the Television functionality. I got it installed and I am able to create an accessory, a television service, a speaker service, a few input services and link them all together.

They show up in the Home app and I can control volume and send button presses from the Remote app as well.

The only thing I can't get to work is to show the accessory as a TV in the Home app.

I've tried doing

```ruby
RubyHome.configure do |c|
   c.discovery_name = 'Television'
   c.category_identifier = :television
 end
```

per the example, but this seems to operate on the Bridge, not the accessory. When I have this configuration, I see a TV icon when adding the bridge to the Home app, but after the accessory is added it displays a house icon instead of a TV.

Any ideas what I'm doing wrong?

**Comment by karlentwistle** [comment]
Hey again @johndbritton 👋 

I just tested this out using the [television example](https://github.com/karlentwistle/ruby_home/blob/master/examples/television.rb) and it appears to work ok for me. 

<img width="300" src="https://user-images.githubusercontent.com/666397/105835291-87690400-5fc3-11eb-907a-e2099635cc52.jpeg" />

Are you using a relatively recent version of iOS - mine is 14.3 

Something else that springs to mind. Your `identifier_cache.yml` might have gotten out of hand while you've been developing on ruby_home. Assuming you don't have any automation setup against your ruby_home television I would try to remove that file and then restart ruby_home. It might fix the issue. 

If that doesn't work could you share the entire script you're trying to run and I can take a look.
