### ISSUE TITLE
New gem version

### ISSUE THREAD

**Issue by AndreasBomholtz** [karlentwistle/ruby_home#17]
Hi,

Is it possible that you can push a new version of you gem? I would like to use some of the changes you made.

Best regards,
Andreas

**Comment by karlentwistle** [comment]
Hey I am currently on vacation but will release an updated as soon as I return.

Cheers 🙂

**Comment by karlentwistle** [comment]
I have returned from vacation 😅

I have just released the updated version 0.1.1

Cheers 🍻
