### ISSUE TITLE
Can't use services other than Fan

### ISSUE THREAD

**Issue by vickash** [karlentwistle/ruby_home#31]
Hi,

I got the basic fan example working properly and then tried changing the fan to a garage door opener with:

~~~~
door = RubyHome::AccessoryFactory.create(:garage_door_opener)

door.characteristic(:target_door_state).on(:updated) do |new_value|
  puts new_value.inspect
end
~~~~

I deleted the bridge from my phone, and the YAML file from my working directory, before running the script again. The bridge shows in the Home app, but after entering the code, I get the error message:

~~~~
Couldn't add RubyHome
Home couldn't connect to this accessory.
~~~~

If, instead of replacing the fan with a garage door opener, I add a second fan to the example, both fans show up and work properly in the Home app.

I'm using ruby 2.5.0p0 on OS X 10.11.6 (El Capitan) and iOS 11.4.1 if that helps. Thanks.

**Comment by karlentwistle** [comment]
Hi @vickash 

Thanks very much for bringing this issue to my attention.

I had a bit of time tonight to fix the immediate issue and was able to successfully get through the pairing process for a `garage_door_opener`.

```
require 'ruby_home'

accessory_information = RubyHome::AccessoryFactory.create(:accessory_information)
door = RubyHome::AccessoryFactory.create(:garage_door_opener)

door.characteristic(:target_door_state).on(:updated) do |new_value|
  puts new_value.inspect
end

RubyHome.run
```

**Comment by karlentwistle** [comment]
@vickash I have fixed the setting https://github.com/karlentwistle/ruby_home/commit/e673699a45fed13ed9f7af1db7560c621bf9414  and getting https://github.com/karlentwistle/ruby_home/commit/79b67c9a216efa8b07de58b8bcd377ccf4ce7742 of characteristics. 

The final issue I am aware of that you will probably run into is https://github.com/karlentwistle/ruby_home/issues/34 I will fix this is due course.

Cheers
