### ISSUE TITLE
Allow customising the bridge name

### ISSUE THREAD

**Issue by lazyatom** [karlentwistle/ruby_home#56]
It'd be neat to be able to change the name of the device (bridge) that appears when you first try to pair, which is I _think_ [defined here](https://github.com/karlentwistle/ruby_home/blob/master/lib/ruby_home/dns/service.rb#L25). Perhaps it could be given as an argument to `RubyHome.run`?

**Comment by karlentwistle** [comment]
Hey @lazyatom that is indeed the correct parameter to change. I’m on holiday at the moment but I can take a look when I return 🙂

**Comment by karlentwistle** [comment]
Hey @lazyatom thanks for the suggestion I've gone ahead and implemented this https://github.com/karlentwistle/ruby_home/pull/62 along with some other customisations that can be made.

I called the attribute you referred to as "bridge name" `discovery_name` so you should be able to set it like this:

```ruby
RubyHome.configure do |c|
  c.discovery_name = 'My House'
end
```

I will merge and release this tomorrow night under `0.1.23` I just want to do some more testing locally before it's 🚢

**Comment by lazyatom** [comment]
Sounds great - thanks for this!
