### ISSUE TITLE
unable to set Typ of Contact Sensor

### ISSUE THREAD

**Issue by andreasgrau** [karlentwistle/ruby_home#60]
in Homekit there are different types of contact sensors available, e.g. door or window.
Setting the typ should be possible when creating services.

**Comment by karlentwistle** [comment]
Hey @andreasgrau thanks for another great suggestion. 

I've just taken a look into this and I am afraid the response is very similar to https://github.com/karlentwistle/ruby_home/issues/61. I don't think this is a currently supported feature within the HomeKit Accessory Protocol Specification. As far as I can tell you have to configure the "type" of contact sensor from within the HomeKit API used by HomeKit apps like the Home app on iOS.

## HAP specification (page 223)

These are the optional and required characteristics for a contact sensor. I cannot see a type attribute that is available:

![screenshot 2019-02-24 at 21 30 38](https://user-images.githubusercontent.com/666397/53305610-706f8380-387b-11e9-8b47-82402ca33fc1.png)

## Configure type

This is where you can configure the type from within the Home application on iOS:

<img src="https://user-images.githubusercontent.com/666397/53305622-9e54c800-387b-11e9-85e3-212e33fff010.jpeg" width="300" />

Test code used:

```ruby
require 'ruby_home'
RubyHome::ServiceFactory.create(:contact_sensor)
RubyHome.run
```
