### ISSUE TITLE
New release for new services?

### ISSUE THREAD

**Issue by cannikin** [karlentwistle/ruby_home#83]
Trying to use the `Valve` service but it's values in the `services.yml` config file don't exist in the latest release, but they are there in `master`. Any plan to push a version update with the latest? Thanks!

**Comment by karlentwistle** [comment]
I've just released version 0.2.3 which includes the new services that were committed in https://github.com/karlentwistle/ruby_home/commit/6ceac7da651e6bced6bbc06c9f16ad02c573dcd6

**Comment by cannikin** [comment]
Thanks!
